# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events.proto',
  package='server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x65vents.proto\x12\x06server\"\x18\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty\"\x1a\n\tTopicList\x12\r\n\x05topic\x18\x01 \x03(\t\"=\n\tOrganizer\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"\x95\x01\n\x0c\x44\x65scripction\x12%\n\norganizers\x18\x01 \x03(\x0b\x32\x11.server.Organizer\x12)\n\x05state\x18\x02 \x01(\x0e\x32\x1a.server.Descripction.State\"3\n\x05State\x12\r\n\tSCHEDULED\x10\x00\x12\x0e\n\nDISSMISSED\x10\x01\x12\x0b\n\x07PENDING\x10\x02\"E\n\x08Location\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0c\n\x04\x66lat\x18\x03 \x01(\x05\x12\r\n\x05\x62lock\x18\x04 \x01(\x05\"l\n\x05\x45vent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x04\x64\x65sc\x18\x02 \x01(\x0b\x32\x14.server.Descripction\x12\"\n\x08location\x18\x03 \x01(\x0b\x32\x10.server.Location\x12\r\n\x05topic\x18\x04 \x03(\t\"1\n\rSubscribction\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\"?\n\x0c\x45ventWrapper\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x1c\n\x05\x65vent\x18\x02 \x01(\x0b\x32\r.server.Event2\xab\x01\n\x06Server\x12-\n\x08\x41\x64\x64\x45vent\x12\r.server.Event\x1a\x10.server.Response\"\x00\x12\x41\n\x0eSubscribeTopic\x12\x15.server.Subscribction\x1a\x14.server.EventWrapper\"\x00\x30\x01\x12/\n\tGetTopics\x12\r.server.Empty\x1a\x11.server.TopicList\"\x00\x62\x06proto3'
)



_DESCRIPCTION_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='server.Descripction.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCHEDULED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISSMISSED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=249,
  serialized_end=300,
)
_sym_db.RegisterEnumDescriptor(_DESCRIPCTION_STATE)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='server.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='server.Response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=48,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='server.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=57,
)


_TOPICLIST = _descriptor.Descriptor(
  name='TopicList',
  full_name='server.TopicList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='server.TopicList.topic', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=85,
)


_ORGANIZER = _descriptor.Descriptor(
  name='Organizer',
  full_name='server.Organizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstname', full_name='server.Organizer.firstname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastname', full_name='server.Organizer.lastname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='server.Organizer.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=148,
)


_DESCRIPCTION = _descriptor.Descriptor(
  name='Descripction',
  full_name='server.Descripction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizers', full_name='server.Descripction.organizers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='server.Descripction.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DESCRIPCTION_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=300,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='server.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='street', full_name='server.Location.street', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='server.Location.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flat', full_name='server.Location.flat', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block', full_name='server.Location.block', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=371,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='server.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='server.Event.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='server.Event.desc', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='server.Event.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='server.Event.topic', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=481,
)


_SUBSCRIBCTION = _descriptor.Descriptor(
  name='Subscribction',
  full_name='server.Subscribction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='server.Subscribction.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='server.Subscribction.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=532,
)


_EVENTWRAPPER = _descriptor.Descriptor(
  name='EventWrapper',
  full_name='server.EventWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='server.EventWrapper.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='server.EventWrapper.event', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=597,
)

_DESCRIPCTION.fields_by_name['organizers'].message_type = _ORGANIZER
_DESCRIPCTION.fields_by_name['state'].enum_type = _DESCRIPCTION_STATE
_DESCRIPCTION_STATE.containing_type = _DESCRIPCTION
_EVENT.fields_by_name['desc'].message_type = _DESCRIPCTION
_EVENT.fields_by_name['location'].message_type = _LOCATION
_EVENTWRAPPER.fields_by_name['event'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['TopicList'] = _TOPICLIST
DESCRIPTOR.message_types_by_name['Organizer'] = _ORGANIZER
DESCRIPTOR.message_types_by_name['Descripction'] = _DESCRIPCTION
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Subscribction'] = _SUBSCRIBCTION
DESCRIPTOR.message_types_by_name['EventWrapper'] = _EVENTWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.Response)
  })
_sym_db.RegisterMessage(Response)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.Empty)
  })
_sym_db.RegisterMessage(Empty)

TopicList = _reflection.GeneratedProtocolMessageType('TopicList', (_message.Message,), {
  'DESCRIPTOR' : _TOPICLIST,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.TopicList)
  })
_sym_db.RegisterMessage(TopicList)

Organizer = _reflection.GeneratedProtocolMessageType('Organizer', (_message.Message,), {
  'DESCRIPTOR' : _ORGANIZER,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.Organizer)
  })
_sym_db.RegisterMessage(Organizer)

Descripction = _reflection.GeneratedProtocolMessageType('Descripction', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPCTION,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.Descripction)
  })
_sym_db.RegisterMessage(Descripction)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  'DESCRIPTOR' : _LOCATION,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.Location)
  })
_sym_db.RegisterMessage(Location)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.Event)
  })
_sym_db.RegisterMessage(Event)

Subscribction = _reflection.GeneratedProtocolMessageType('Subscribction', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBCTION,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.Subscribction)
  })
_sym_db.RegisterMessage(Subscribction)

EventWrapper = _reflection.GeneratedProtocolMessageType('EventWrapper', (_message.Message,), {
  'DESCRIPTOR' : _EVENTWRAPPER,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:server.EventWrapper)
  })
_sym_db.RegisterMessage(EventWrapper)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='server.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=600,
  serialized_end=771,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddEvent',
    full_name='server.Server.AddEvent',
    index=0,
    containing_service=None,
    input_type=_EVENT,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeTopic',
    full_name='server.Server.SubscribeTopic',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBCTION,
    output_type=_EVENTWRAPPER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTopics',
    full_name='server.Server.GetTopics',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TOPICLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
